.before_template:
  before_script: &before_definition
    - cd ..
    - rm -fr tkl-debops-test
    - git clone $TKL_DEBOPS_TEST_REPO
    - cd tkl-debops-test
    - ln -s $CI_PROJECT_DIR tkl-debops
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
    - touch ~/.ssh/known_hosts
    - ansible-playbook playbooks/setup.yml
    - echo -e "cat > ansible/inventory/hosts <<EOF\nlxc-host $LXC_HOST_OPTS\n\n[lxc_hosts]\nlxc-host\nEOF" | bash

.job_template: &job_definition
  stage: test
  before_script: *before_definition
  script:
    - ./test_app $APP_NAME $APP_PORT test
  artifacts:
    paths:
      - ansible/inventory/inv_${APP_NAME}_${APP_PORT}
    expire_in: 1 day
    when: on_failure

stages:
  - test
  - cleanup_test
  - publish

test_core:
  <<: *job_definition
  variables:
    APP_NAME: "core"
    APP_PORT: "2222"

test_fileserver:
  <<: *job_definition
  variables:
    APP_NAME: "fileserver"
    APP_PORT: "2223"

test_mediaserver:
  <<: *job_definition
  variables:
    APP_NAME: "mediaserver"
    APP_PORT: "2224"

test_openldap:
  <<: *job_definition
  variables:
    APP_NAME: "openldap"
    APP_PORT: "2225"

cleanup_test_failure:
  stage: cleanup_test
  before_script: *before_definition
  script:
    - ls -l ansible/inventory
    - (files=$(find ansible/inventory/ -maxdepth 1 -type f -name inv_*); for file in $files; do app=$(echo $file | cut -d'_' -f2 | sed -e 's/_//g'); port=$(echo $file | cut -d'_' -f3 | sed -e 's/_//g'); echo Cleaning up $app on $port; ./test_app $app $port stop; done);
    - ls -l ansible/inventory
  when: on_failure

publish_github:
  stage: publish
  script:
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
    - echo "host github.com\n  HostName github.com\n  IdentityFile /ssh/id_rsa" > ~/.ssh/config
    - chmod 600 ~/.ssh/config
    - touch ~/.ssh/known_hosts
    - ssh-keyscan -H github.com > ~/.ssh/known_hosts
    - git remote add github git@github.com:jstruebel/tkl-debops.git
    - git fetch github
    - git push github "$CI_BUILD_REF_NAME" -f
