---

- name: Setup Ansible and Debops for tkl-debops project
  hosts: localhost
  connection: local

  vars:
    apt_pkgs:
      - 'python-pip'
    pip_pkgs:
      - { name: 'ansible', version: '2.3' }
      - { name: 'jinja2', version: '2.8.1' }
      - { name: 'debops', version: '0.4.4' }
    init_script_dir: '{{ playbook_dir }}/../../'
    init_script: 'tkl-debops-init'

  tasks:
    - name: Install required apt packages
      apt:
        name: '{{ item }}'
        state: latest
        update_cache: yes
      become: True
      with_items: '{{ apt_pkgs }}'

    - name: Install correct version of ansible, debops and dependencies
      pip:
        name: '{{ item.name }}'
        version: '{{ item.version }}'
        state: 'present'
      become: True
      with_items: '{{ pip_pkgs }}'

    - name: Install or update debops playbooks
      command: debops-update
      args:
        chdir: '{{ init_script_dir }}'

    - name: Initialize project
      command: '{{ init_script_dir + init_script }}'
      args:
        chdir: '{{ init_script_dir }}'
