---
# Changes to default DebOps postfix role for Turnkey Linux configuration

postfix__smtpd_banner: '$myhostname ESMTP $mail_name (Debian/GNU)'

postfix__maincf:
  - name: 'disable_vrfy_command'
    value: False
    section: 'restrictions'

  - name: 'enable_long_queue_ids'
    value: False
    section: 'base'
    state: 'present'

  - name: 'inet_interfaces'
    value: 'localhost'
    section: 'base'

  - name: 'strict_rfc821_envelopes'
    value: False
    section: 'restrictions'

  - name: 'smtpd_helo_required'
    value: False
    section: 'restrictions'

  - name: 'smtpd_reject_unlisted_sender'
    value: False
    section: 'restrictions'

  - name: 'smtpd_client_restrictions'
    value: ''
    section: 'restrictions'
    state: 'absent'

  - name: 'smtpd_data_restrictions'
    section: 'restrictions'
    weight: 60
    value: ''

  - name: 'smtpd_helo_restrictions'
    section: 'restrictions'
    weight: 20
    value: ''

  - name: 'smtpd_recipient_restrictions'
    section: 'restrictions'
    weight: 50
    value: ''

  - name: 'smtpd_sender_restrictions'
    section: 'restrictions'
    weight: 30
    value: ''
