---
# Changes to default DebOps sshd role for Turnkey Linux configuration

sshd__recommended_packages: []

sshd__optional_packages: []

sshd__host_keys: [ 'rsa', 'dsa', 'ecdsa', 'ed25519' ]

sshd__permit_root_login: 'yes'

sshd__password_authentication: 'yes'

sshd__x11_forwarding: 'yes'

sshd__max_auth_tries: '6'

sshd__max_startups: '10:30:100'

sshd__login_grace_time: '120'

sshd__privilege_separation: 'yes'

sshd__default_allow_groups: []

sshd__authorized_keys_system: []

sshd__authorized_keys_user:
  - '.ssh/authorized_keys'
  - '.ssh/authorized_keys2'

sshd__ciphers_map:
  # Source: Default Turnkey Linux settings
  '6.7': [ '3des-cbc', 'blowfish-cbc', 'cast128-cbc', 'arcfour', 'arcfour128', 'arcfour256',
           'aes128-cbc', 'aes192-cbc', 'aes256-cbc', 'rijndael-cbc@lysator.liu.se', 'aes128-ctr',
           'aes192-ctr', 'aes256-ctr', 'aes128-gcm@openssh.com', 'aes256-gcm@openssh.com',
           'chacha20-poly1305@openssh.com' ]

  # Source: https://wiki.mozilla.org/Security/Guidelines/OpenSSH
  '6.5': [ 'chacha20-poly1305@openssh.com', 'aes256-gcm@openssh.com',
           'aes128-gcm@openssh.com', 'aes256-ctr', 'aes192-ctr',
           'aes128-ctr' ]

  # Source: https://xivilization.net/~marek/blog/2015/01/12/secure-secure-shell-on-debian-wheezy/
  '6.0': [ 'aes256-ctr', 'aes192-ctr', 'aes128-ctr' ]


sshd__kex_algorithms_map:
  # Source: Default Turnkey Linux settings
  '6.7': [ 'diffie-hellman-group1-sha1', 'diffie-hellman-group14-sha1',
           'diffie-hellman-group-exchange-sha1', 'diffie-hellman-group-exchange-sha256',
           'ecdh-sha2-nistp256', 'ecdh-sha2-nistp384', 'ecdh-sha2-nistp521',
           'diffie-hellman-group1-sha1', 'curve25519-sha256@libssh.org' ]

  # Source: https://wiki.mozilla.org/Security/Guidelines/OpenSSH
  '6.5': [ 'curve25519-sha256@libssh.org', 'ecdh-sha2-nistp521',
           'ecdh-sha2-nistp384', 'ecdh-sha2-nistp256',
           'diffie-hellman-group-exchange-sha256' ]

  # Source: https://xivilization.net/~marek/blog/2015/01/12/secure-secure-shell-on-debian-wheezy/
  '6.0': [ 'diffie-hellman-group-exchange-sha256' ]


sshd__macs_map:
  # Source: Default Turnkey Linux settings
  '6.7': [ 'hmac-sha1', 'hmac-sha1-96', 'hmac-sha2-256', 'hmac-sha2-512', 'hmac-md5',
           'hmac-md5-96', 'hmac-ripemd160', 'hmac-ripemd160@openssh.com', 'umac-64@openssh.com',
           'umac-128@openssh.com', 'hmac-sha1-etm@openssh.com', 'hmac-sha1-96-etm@openssh.com',
           'hmac-sha2-256-etm@openssh.com', 'hmac-sha2-512-etm@openssh.com',
           'hmac-md5-etm@openssh.com', 'hmac-md5-96-etm@openssh.com',
           'hmac-ripemd160-etm@openssh.com', 'umac-64-etm@openssh.com',
           'umac-128-etm@openssh.com' ]

  # Source: https://wiki.mozilla.org/Security/Guidelines/OpenSSH
  '6.5': [ 'hmac-sha2-512-etm@openssh.com', 'hmac-sha2-256-etm@openssh.com',
           'umac-128-etm@openssh.com', 'hmac-sha2-512', 'hmac-sha2-256',
           'umac-128@openssh.com' ]

  # Source: https://xivilization.net/~marek/blog/2015/01/12/secure-secure-shell-on-debian-wheezy/
  '6.0': [ 'hmac-sha2-512', 'hmac-sha2-256', 'hmac-ripemd160' ]


sshd__moduli_minimum: '1022'

sshd__ldap_filter: '{{ sshd__ldap_filter_map["uid"] }}'

sshd__ldap_filter_map:

  # User account by uid attribute only
  'uid': '(&(objectClass=posixAccount)(uid=$username))'

  # User account needs 'authorizedService' attribute
  'service': '(&(objectClass=posixAccount)(uid=$username)(authorizedService=$service))'

  # User account needs 'host' attribute
  'host': '(&(objectClass=posixAccount)(uid=$username)(|(host=$hostname)(host=$fqdn)(host=\\*.$domain)(host=\\*)))'

  # User account needs both 'authorizedService' and 'host' attributes.
  'service+host': '(&(objectClass=posixAccount)(uid=$username)(authorizedService=$service)(|(host=$hostname)(host=$fqdn)(host=\\*.$domain)(host=\\*)))'

sshd__match_list:
  - match: 'user root'
    options: |
      Banner /root/.ssh/banner
  - match: 'user *'
    options: ''

sshd__custom_options: |
  UseDNS no
